# Generated by Django 5.0.4 on 2025-07-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asanawebhookrequestdata",
            name="is_target_event",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("event_data", models.JSONField()),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asana.asanawebhookrequestdata",
                    ),
                ),
            ],
        ),
    ]
