# Generated by Django 5.0.4 on 2025-07-22 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0002_asanawebhookrequestdata_is_target_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedtask",
            name="task_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
